apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wordsmith-servicemonitor
  namespace: monitoring-demo
spec:
  selector:
    matchLabels:
      app: api
  endpoints:
  - port: metrics
    interval: 15s
