apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: api
    - port: 8734
      targetPort: 8734
      name: metrics
  selector:
    app: api
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: harbor.dnavarrete-tf-do-rke.do.support.rancher.space/wordsmith/wordsmith-api:1.0.2
          ports:
            - containerPort: 8080
              name: api
            - containerPort: 8734
              name: metrics
